const cardData = [
    {
        imageSrc: window.location.origin + '/images/GroceryImage/dry1.jpg',
        title: 'Dry fruits',
        localPrice: '1000',
        discount:'9',
        category:'Dry',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/onion2.jpg',
        title: 'Onion',
        localPrice: '40',
        discount:'1',
        category:'Onion',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/tomato3.jpg',
        title: 'Tomato',
        localPrice: '150',
        discount:'0',
        category:'Tomato',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/dal1.jpg',
        title: 'Dal',
        localPrice: '120',
        discount:'4',
        category:'Dal',
    },
    
    {
        imageSrc: window.location.origin + '/images/GroceryImage/suger2.jpg',
        title: 'Suger',
        localPrice: '45',
        discount:'2',
        category:'Suger',
    },
    
    {
        imageSrc: window.location.origin + '/images/GroceryImage/dry5.jpg',
        title: 'Dry fruits',
        localPrice: '1200',
        discount:'10',
        category:'dry',
        category:'almond',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/tomato1.jpg',
        title: 'Tomato',
        localPrice: '200',
        discount:'14',
        category:'Tomato',
    },
    
    {
        imageSrc: window.location.origin + '/images/GroceryImage/dry9.jpg',
        title: 'Drt fruits',
        localPrice: '400',
        discount:'17',
        category:'Dry',
    },
    
    {
        imageSrc: window.location.origin + '/images/GroceryImage/flour2.jpg',
        title: 'Flour',
        localPrice: '380',
        discount:'1',
        category:'Flour',
    },
    
    {
        imageSrc: window.location.origin + '/images/GroceryImage/flour4.jpg',
        title: 'Flour',
        localPrice: '420',
        discount:'15',
        category:'Flour',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/ginger1.jpg',
        title: 'Ginger',
        localPrice: '280',
        discount:'0',
        category:'Ginger',
    },
    
    {
        imageSrc: window.location.origin + '/images/GroceryImage/ginger3.jpg',
        title: 'Ginger',
        localPrice: '300',
        discount:'10',
        category:'Ginger',
    },
    
    {
        imageSrc: window.location.origin + '/images/GroceryImage/oil1.jpg',
        title: 'Oil',
        localPrice: '165',
        discount:'6',
        category:'Oil',
    },

    {
        imageSrc: window.location.origin + '/images/GroceryImage/ginger2.jpg',
        title: 'Ginger',
        localPrice: '300',
        discount:'10',
        category:'Ginger',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/dry2.jpg',
        title: 'Drt fruits',
        localPrice: '400',
        discount:'17',
        category:'Dry',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/oil3.jpg',
        title: 'Oil',
        localPrice: '165',
        discount:'6',
        category:'Oil',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/onion1.jpg',
        title: 'Onion',
        localPrice: '40',
        discount:'1',
        category:'Onion',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/oil3.jpg',
        title: 'Oil',
        localPrice: '165',
        discount:'6',
        category:'Oil',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/onion3.jpg',
        title: 'Onion',
        localPrice: '40',
        discount:'1',
        category:'Onion',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/pea1.jpg',
        title: 'This is Electronic Rice. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '20/month',
        category:'Rice',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/dry10.jpg',
        title: 'Drt fruits',
        localPrice: '400',
        discount:'17',
        category:'Dry',
    },
    
    {
        imageSrc: window.location.origin + '/images/GroceryImage/pea2.jpg',
        title: 'This is Electronic Rice. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '20/month',
        category:'Rice',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/soap6.jpg',
        title: 'This is Electronic Rice. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '20/month',
        category:'Rice',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/dry11.jpg',
        title: 'Drt fruits',
        localPrice: '400',
        discount:'17',
        category:'Dry',
    },
    
    {
        imageSrc: window.location.origin + '/images/GroceryImage/potato.jpg',
        title: 'This is Electronic Rice. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '20/month',
        category:'Rice',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/rice1.jpg',
        title: 'This is Electronic Rice. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '20/month',
        category:'Rice',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/soap5.jpg',
        title: 'Soap',
        localPrice: '12',
        discount:'2',
        category:'Soap',
    },
    
    {
        imageSrc: window.location.origin + '/images/GroceryImage/soap3.jpg',
        title: 'Soap',
        localPrice: '12',
        discount:'2',
        category:'Soap',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/pea3.jpg',
        title: 'Pea',
        localPrice: '200',
        discount:'10',
        category:'Pea',
    },
    
    {
        imageSrc: window.location.origin + '/images/GroceryImage/rice2.jpg',
        title: 'Rice',
        localPrice: '90',
        discount:'16',
        category:'Rice',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/dry12.jpg',
        title: 'Drt fruits',
        localPrice: '400',
        discount:'17',
        category:'Dry',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/soap4.jpg',
        title: 'Soap',
        localPrice: '12',
        discount:'2',
        category:'Soap',
    },
    
    {
        imageSrc: window.location.origin + '/images/GroceryImage/pea4.jpg',
        title: 'Pea',
        localPrice: '230',
        discount:'9',
        category:'Pea',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/rice3.jpg',
        title: 'Rice',
        localPrice: '80',
        discount:'13',
        category:'Rice',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/soap1.jpg',
        title: 'Soap',
        localPrice: '12',
        discount:'2',
        category:'Soap',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/dal3.jpg',
        title: 'Dal',
        localPrice: '120',
        discount:'10',
        category:'Dal',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/soap2.jpg',
        title: 'Soap',
        localPrice: '12',
        discount:'2',
        category:'Soap',
    },
    
    
    {
        imageSrc: window.location.origin + '/images/GroceryImage/dry4.jpg',
        title: 'Drt fruits',
        localPrice: '400',
        discount:'17',
        category:'Dry',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/suger1.jpg',
        title: 'Suger',
        localPrice: '40',
        discount:'4',
        category:'Suger',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/dal4.jpg',
        title: 'Dal',
        localPrice: '120',
        discount:'10',
        category:'Dal',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/dry7.jpg',
        title: 'Drt fruits',
        localPrice: '400',
        discount:'17',
        category:'Dry',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/dry8.jpg',
        title: 'Drt fruits',
        localPrice: '400',
        discount:'17',
        category:'Dry',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/dry6.jpg',
        title: 'Drt fruits',
        localPrice: '400',
        discount:'17',
        category:'Dry',
    },
    
    {
        imageSrc: window.location.origin + '/images/GroceryImage/tomato1.jpg',
        title: 'Tomato',
        localPrice: '280',
        discount:'10',
        category:'Tomato',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/flour3.jpg',
        title: 'Flour',
        localPrice: '400',
        discount:'10',
        category:'Flour',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/tomato2.jpg',
        title: 'Tomato',
        localPrice: '280',
        discount:'10',
        category:'Tomato',
    },
    {
        imageSrc: window.location.origin + '/images/GroceryImage/dal2.jpg',
        title: 'Dal',
        localPrice: '120',
        discount:'10',
        category:'Dal',
    },
    
    {
        imageSrc: window.location.origin + '/images/GroceryImage/dry3.jpg',
        title: 'Dry fruits',
        localPrice: '400',
        discount:'17',
        category:'Dry',
    },
]
export function GroceryItem() {
    return cardData;
    }