const cardData = [
    {
        imageSrc: window.location.origin + '/images/sliderImage/c3.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c8.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '120',
        localPrice: '6000',
        discount:'10',
        emi: '$25/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c7.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c9.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c1.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c4.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c1.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c1.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c1.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c1.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c1.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c1.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c1.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c1.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c8.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '120',
        localPrice: '6000',
        discount:'10',
        emi: '$25/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c7.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c9.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c1.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c4.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c1.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c1.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c1.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c1.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c1.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c1.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c1.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
    {
        imageSrc: window.location.origin + '/images/sliderImage/c1.jpg',
        title: 'This is Electronic Mobile. It have best price for sale',
        price: '100',
        localPrice: '5000',
        discount:'10',
        emi: '$20/month',
    },
  // Add more card data objects as needed
];
export function HomeItem() {
    return cardData;
    }